version: '2'
services:
  postgres:
    image: postgres:12-alpine
    container_name: dishdash-db
    networks:
      - local_net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: dishdash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:latest
    container_name: dishdash-redis
    networks:
      - local_net
    ports:
      - "6379:6379"
networks:
  local_net:
    driver: bridge